image: $GITLAB_NODE_BUILD_IMAGE

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - bower install --allow-root
    - gulp
  artifacts:
        paths:
            - dist/
  tags:
    - builder

deploy:
  stage: deploy
  script:
    - npm install
    - 'bower register "$CI_PROJECT_NAME" "$CI_PROJECT_URL".git --allow-root --config.registry.register="$NEXUS_BOWER_URL"'
  tags:
    - builder